const fs = require('fs');

const moreReading = [
  {
    "title": "CLB 11-12 Reading Part 3: Reading for Information (Science)",
    "passage": "A\nThe global transition towards renewable energy has spotlighted lithium-ion batteries as the critical bottleneck in widespread electric vehicle (EV) adoption. While lithium extraction has historically relied on environmentally taxing brine evaporation ponds in South America or hard-rock mining in Australia, recent geopolitical pressures have forced nations to seek domestic alternatives. Direct Lithium Extraction (DLE) has emerged as a promising, albeit unproven, technological savior. DLE utilizes highly selective chemical sorbents to pull lithium directly from underground geothermal brines, theoretically reducing the land footprint and water consumption associated with traditional methods by up to 90%.\n\nB\nDespite its theoretical advantages, the commercialization of DLE faces significant engineering hurdles. The chemical sorbents degrade rapidly when exposed to the extreme temperatures and varied mineral compositions of natural geothermal brines. Consequently, the operational costs of constantly replacing these materials often render DLE economically unviable compared to traditional mining. Furthermore, the process requires massive amounts of fresh water for the final purification stages, sparking fierce opposition from environmental groups in arid regions where pilot plants have been proposed. Thus, while politicians champion DLE as a 'green' alternative, industrial chemists remain highly skeptical of its near-term scalability.\n\nC\nIn parallel, research into solid-state batteries (SSBs) threatens to disrupt the lithium market entirely. SSBs replace the flammable liquid electrolyte found in conventional lithium-ion cells with a solid ceramic or polymer material. This architectural shift not only drastically reduces the risk of battery fires but also allows for the use of pure lithium metal anodes, potentially doubling the energy density of the battery. If successfully scaled, SSBs would enable EVs to travel over 1,000 kilometers on a single charge, effectively eliminating consumer range anxiety.\n\nD\nHowever, the mass production of SSBs is impeded by the 'solid-solid interface problem.' As the battery charges and discharges, the lithium metal anode expands and contracts. In a rigid solid-state system, this microscopic movement causes the ceramic electrolyte to crack over time, leading to catastrophic battery failure after only a few hundred cycles. Major automotive manufacturers have invested billions into solving this durability issue, employing complex pressure-containment mechanisms and flexible polymer coatings. Yet, a commercially viable SSB that can withstand the 10-year lifespan demanded by the automotive industry remains frustratingly out of reach.",
    "questions": [
      { "text": "Which paragraph details the physical degradation of battery components over time?", "options": ["A", "B", "C", "D"], "correctAnswerIndex": 3 },
      { "text": "Which paragraph mentions the geographical sources of traditional lithium mining?", "options": ["A", "B", "C", "D"], "correctAnswerIndex": 0 },
      { "text": "Which paragraph discusses the unexpected environmental pushback against a supposedly green technology?", "options": ["A", "B", "C", "D"], "correctAnswerIndex": 1 },
      { "text": "Which paragraph explains a technological improvement that prevents batteries from catching fire?", "options": ["A", "B", "C", "D"], "correctAnswerIndex": 2 },
      { "text": "What is the primary reason industrial chemists are skeptical of DLE?", "options": ["It produces highly flammable liquid electrolytes.", "The chemical sorbents are too expensive to replace constantly.", "It requires hard-rock mining in Australia.", "The lithium produced is not pure enough for EVs."], "correctAnswerIndex": 1 },
      { "text": "The 'solid-solid interface problem' is caused by:", "options": ["Geopolitical pressures forcing domestic production.", "The expansion and contraction of the lithium metal anode.", "The use of highly selective chemical sorbents.", "Fresh water shortages in arid regions."], "correctAnswerIndex": 1 }
    ]
  },
  {
    "title": "CLB 11-12 Reading Part 1: Reading Correspondence (Corporate)",
    "passage": "Dear Management Team,\n\nI am writing to formally present the findings from our Q3 internal audit regarding the mandatory 'Return to Office' (RTO) policy implemented last January. As you are aware, the directive required all non-essential staff to be physically present at the downtown headquarters for a minimum of three days a week. The intention, as outlined by the CEO, was to foster spontaneous collaboration and revitalize our corporate culture.\n\nUnfortunately, the data indicates a starkly different reality. Our internal metrics show a 14% decline in overall departmental productivity compared to the fully remote model we utilized last year. The primary driver of this decline appears to be the 'context switching' forced upon employees in the open-plan office. According to the anonymous employee surveys we conducted, 78% of staff report that the constant noise and interruptions make deep, focused work nearly impossible. \n\nFurthermore, our HR attrition data is alarming. Since the RTO policy was enforced, voluntary turnover has spiked by 22%, with the majority of departing employees citing the reinstatement of their daily commute as the primary reason for leaving. Most concerning is that we are disproportionately losing our senior software architects—the very talent we can least afford to replace in the current competitive market.\n\nWhile I understand the Executive Board's desire to justify the 10-year commercial lease on the building, forcing attendance is actively harming our output. I strongly recommend that we immediately pivot to a 'hub-and-spoke' model. This would allow teams to use the headquarters strictly for scheduled, collaborative workshops once a month, while permitting them to execute their daily tasks remotely. \n\nI have attached the full statistical breakdown to this email. I kindly request that this issue be added to the agenda for next Tuesday's strategic planning session.\n\nSincerely,\nElena Rostova\nDirector of Operations",
    "questions": [
      { "text": "What was the CEO's original reason for implementing the RTO policy?", "options": ["To justify the cost of the commercial lease.", "To improve spontaneous collaboration and corporate culture.", "To reduce the voluntary turnover rate.", "To conduct an internal audit on employee productivity."], "correctAnswerIndex": 1 },
      { "text": "According to the email, why did productivity decline?", "options": ["Employees were spending too much time commuting.", "Senior software architects were refusing to work.", "The open-plan office caused constant interruptions.", "The CEO changed the company's strategic goals."], "correctAnswerIndex": 2 },
      { "text": "What does Elena Rostova suggest the company do with the headquarters?", "options": ["Sell the building and cancel the lease.", "Use it only for scheduled collaborative workshops once a month.", "Require employees to work there five days a week.", "Convert it into a hub for senior software architects."], "correctAnswerIndex": 1 },
      { "text": "What does the HR data reveal about the company's staff?", "options": ["78% of employees have threatened to quit.", "Senior staff are leaving the company at an alarming rate.", "Employees are asking for longer commutes.", "The company is hiring faster than competitors."], "correctAnswerIndex": 1 }
    ]
  }
];

const moreListening = [
  {
    "title": "CLB 11-12 Listening Part 5: Listening to a Discussion (Urban Dev)",
    "transcript": "[Three people: Mayor Lin, Architect Davis, and Citizen Representative Chen]\n\nLin: Let's discuss the proposed waterfront redevelopment. The developers want to build three luxury high-rises, which would generate millions in property taxes for the city.\n\nChen: Mayor Lin, the community is entirely against this. That waterfront is the last stretch of public green space in the district. If you let them build luxury condos, you're effectively privatizing the view and pushing out the working-class families who have lived here for decades.\n\nDavis: Mr. Chen, I understand the gentrification concerns, but the current green space is severely unmaintained and unsafe at night. Our architectural proposal includes a mandated public boardwalk along the water and a commercial plaza on the ground floors. We aren't closing off the water; we're revitalizing it.\n\nChen: A commercial plaza filled with expensive boutique cafes doesn't serve the local community, Davis. It caters to the wealthy people buying the condos. What the district actually needs is an upgraded community center and a modernized public park.\n\nLin: We don't have the municipal budget to upgrade that park ourselves, Chen. The city is facing a massive deficit. The developers have offered to fully fund the construction of a new community center nearby, but only if we approve the high-rises. It's a trade-off.\n\nChen: It's blackmail. They know the city is broke, so they're buying the zoning rights. If you approve this, you set a precedent that public land is for sale to the highest bidder.\n\nDavis: It's not public land for sale, it's a public-private partnership. The developers take on the financial risk, and the city gets a new community center and increased tax revenue without raising income taxes on the residents.\n\nLin: Exactly. If we reject this proposal, the waterfront remains a derelict safety hazard for the next ten years. I believe the long-term economic benefits outweigh the immediate disruption.",
    "questions": [
      { "text": "What is the main conflict of the discussion?", "options": ["Whether to raise municipal income taxes.", "Whether to allow luxury condos on the waterfront.", "How to fund a new public boardwalk.", "Who should design the new community center."], "correctAnswerIndex": 1 },
      { "text": "Why does Mayor Lin support the developers' proposal?", "options": ["Because the city doesn't have the money to fix the park itself.", "Because he wants to privatize the entire waterfront.", "Because the local residents voted for it.", "Because it will lower property taxes for working-class families."], "correctAnswerIndex": 0 },
      { "text": "What does the architect, Davis, claim the developers will include for the public?", "options": ["Free apartments for working-class families.", "A mandated public boardwalk and commercial plaza.", "A reduction in city income taxes.", "A completely private, gated community."], "correctAnswerIndex": 1 },
      { "text": "How does Chen describe the developers' offer to build a community center?", "options": ["As a generous public-private partnership.", "As a necessary compromise for the city.", "As blackmail to buy zoning rights.", "As a solution to the safety hazards."], "correctAnswerIndex": 2 },
      { "text": "What does Mayor Lin predict will happen if they reject the proposal?", "options": ["The city will raise income taxes immediately.", "The waterfront will remain unsafe and abandoned.", "The developers will build the community center anyway.", "Working-class families will move out of the district."], "correctAnswerIndex": 1 }
    ]
  }
];

let rData = JSON.parse(fs.readFileSync('celpip_reading.json', 'utf8'));
let lData = JSON.parse(fs.readFileSync('celpip_listening.json', 'utf8'));

rData = [...rData, ...moreReading];
lData = [...lData, ...moreListening];

fs.writeFileSync('celpip_reading.json', JSON.stringify(rData, null, 2));
fs.writeFileSync('celpip_listening.json', JSON.stringify(lData, null, 2));
fs.writeFileSync('celpip_data.js', 'const readingData = ' + JSON.stringify(rData) + ';\nconst listeningData = ' + JSON.stringify(lData) + ';');
